# Generated by Django 6.0.4 on 2026-05-09 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Data e hora da corrida')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthDate', models.DateField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('clothingSize', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunnerSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signUpDate', models.DateTimeField(auto_now_add=True)),
                ('classification', models.IntegerField(blank=True, null=True)),
                ('adminComment', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], max_length=20)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.profile')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signUpDate', models.DateTimeField(auto_now_add=True)),
                ('adminComment', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], max_length=20)),
                ('role', models.CharField(choices=[('ENTREGA_DORSAIS', 'Entrega de Dorsais'), ('APOIO_PARTIDA', 'Apoio na Partida'), ('COACH_BANCADA', 'Coach de Bancada'), ('ORIENTACAO', 'Orientação'), ('ABASTECIMENTOS', 'Abastecimentos'), ('SEGURANCA', 'Segurança'), ('PRIMEIROS_SOCORROS', 'Primeiros Socorros'), ('PACER', 'Pacer')], max_length=30)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.profile')),
            ],
        ),
    ]
