# Generated by Django 6.0.4 on 2026-05-08 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminComment', models.CharField(max_length=200)),
                ('classification', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunnerSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signUpDate', models.DateTimeField(verbose_name='Data e hora da Inscricao')),
                ('state', models.CharField(choices=[(3, 'Cancelada'), (1, 'Banida'), (2, 'Ativa')])),
                ('classification', models.IntegerField()),
                ('admincomment', models.TextField()),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='race.race')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='race.runner')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoluntarySignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signUpDate', models.DateTimeField(verbose_name='Data e hora da Inscricao')),
                ('role', models.CharField(choices=[(1, 'EntregaDorsais'), (2, 'ApoioNaPartida'), (3, 'CoachDeBancada'), (4, 'Orientacao'), (5, 'Abatescimentos'), (6, 'Seguranca'), (7, 'PrimeirosSocorros'), (8, 'Pacer')])),
                ('state', models.CharField(choices=[(1, 'Pendente'), (2, 'Aprovado'), (3, 'Rejeitado')])),
                ('admincomment', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='race.voluntary')),
            ],
        ),
    ]
