# Generated by Django 6.0.4 on 2026-05-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runnersignup',
            old_name='signUpDate',
            new_name='signupDate',
        ),
        migrations.RenameField(
            model_name='volunteersignup',
            old_name='signUpDate',
            new_name='signupDate',
        ),
    ]
