# Generated by Django 6.0.4 on 2026-05-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_runner_runnersignup_voluntary_voluntarysignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnersignup',
            name='state',
            field=models.CharField(choices=[(1, 'Banida'), (2, 'Ativa'), (3, 'Cancelada')]),
        ),
        migrations.AlterField(
            model_name='runnersignup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.runner'),
        ),
    ]
