# Generated by Django 6.0.4 on 2026-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_alter_runnersignup_state_alter_runnersignup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnersignup',
            name='state',
            field=models.CharField(choices=[(3, 'Cancelada'), (1, 'Banida'), (2, 'Ativa')]),
        ),
    ]
