# Generated by Django 6.0.4 on 2026-05-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_alter_runnersignup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnersignup',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race'),
        ),
    ]
